# Generated by Django 4.2 on 2025-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[
                    ("DOG", "Dog"),
                    ("CAT", "Cat"),
                    ("BIRD", "Bird"),
                    ("FISH", "Fish"),
                ],
                max_length=6,
            ),
        ),
    ]
